### ISSUE TITLE
ImportError: cannot import name Celery

### ISSUE THREAD

**Issue by kpoman** [citizen-stig/celery-with-flask-factories#1]
Hi ! I just cloned the repo and installed all dependencies. I am getting this stacktrace:

```
kpoman@kpoman-ThinkPad-X230 ~/flask-celery-factory/celery-with-flask-factories $ python myapp.py 
Traceback (most recent call last):
  File "myapp.py", line 2, in <module>
    from factories.application import create_application
  File "/home/kpoman/flask-celery-factory/celery-with-flask-factories/factories/application.py", line 4, in <module>
    from controllers import home
  File "/home/kpoman/flask-celery-factory/celery-with-flask-factories/controllers.py", line 3, in <module>
    from factories.celery import create_celery
  File "/home/kpoman/flask-celery-factory/celery-with-flask-factories/factories/celery.py", line 2, in <module>
    from celery import Celery
ImportError: cannot import name Celery
kpoman@kpoman-ThinkPad-X230 ~/flask-celery-factory/celery-with-flask-factories $ 
```

I suppose it is related to some circular imports. I wonder how you could make this work ! Thank you !

**Comment by citizen-stig** [comment]
@kpoman , last message says that Celery is not installed in your python environment:

```
ImportError: cannot import name Celery
```
Please double check, that celery is installed. You can run something like this to check:
```$ pip freeze | grep -i celery
celery==4.1.0
```

**Comment by kpoman** [comment]
I could make it work by renaming celery.py to fcelery.py (and related imports of it).
